import { useCallback, useEffect, useState } from 'react'
import client from '@/api/client'
import type { AdminUser, ApiError, BranchResponse, PagedResponse, RoleResponse } from '@/types/api'

const empty = { email: '', displayName: '', password: '', phone: '' }
export default function AdminUsers() {
  const [items,setItems]=useState<AdminUser[]>([]),[roles,setRoles]=useState<RoleResponse[]>([]),[branches,setBranches]=useState<BranchResponse[]>([])
  const [search,setSearch]=useState(''),[active,setActive]=useState(''),[form,setForm]=useState(empty),[selected,setSelected]=useState<AdminUser|null>(null)
  const [error,setError]=useState(''),[busy,setBusy]=useState(false)
  const load=useCallback(async()=>{const r=await client.get<PagedResponse<AdminUser>>('/users',{params:{search:search||undefined,isActive:active||undefined,pageSize:100}});setItems(r.data.items)},[search,active])
  useEffect(()=>{Promise.all([client.get<PagedResponse<AdminUser>>('/users',{params:{search:search||undefined,isActive:active||undefined,pageSize:100}}),client.get<RoleResponse[]>('/roles'),client.get<PagedResponse<BranchResponse>>('/branches',{params:{pageSize:100}})]).then(([u,r,b])=>{setItems(u.data.items);setRoles(r.data);setBranches(b.data.items)}).catch(e=>setError(e.message))},[search,active])
  async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await client.post('/users',form);setForm(empty);await load()}catch(e){setError((e as ApiError).message)}finally{setBusy(false)}}
  async function toggle(user:AdminUser){try{await client.patch(`/users/${user.id}/status`,{isActive:!user.isActive});await load()}catch(e){setError((e as ApiError).message)}}
  async function role(user:AdminUser,r:RoleResponse,on:boolean){try{await client[on?'put':'delete'](`/users/${user.id}/roles/${r.id}`);await load();setSelected(null)}catch(e){setError((e as ApiError).message)}}
  async function branch(user:AdminUser,b:BranchResponse,on:boolean){try{if(on)await client.put(`/users/${user.id}/branches/${b.id}`,null,{params:{isPrimary:!user.branches.length}});else await client.delete(`/users/${user.id}/branches/${b.id}`);await load();setSelected(null)}catch(e){setError((e as ApiError).message)}}
  return <section><p className="text-sm text-slate-500">Quản trị hệ thống</p><h1 className="text-3xl font-bold">Tài khoản & phân công</h1>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}
    <form onSubmit={create} className="mt-6 grid gap-3 rounded-2xl bg-white p-5 shadow-sm lg:grid-cols-5"><input required type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="rounded-xl border p-3"/><input required minLength={2} placeholder="Họ tên" value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})} className="rounded-xl border p-3"/><input required minLength={6} type="password" placeholder="Mật khẩu ban đầu" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} className="rounded-xl border p-3"/><input placeholder="Số điện thoại" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} className="rounded-xl border p-3"/><button disabled={busy} className="rounded-xl bg-primary-600 font-semibold text-white">Tạo tài khoản</button></form>
    <div className="mt-5 flex gap-3"><input placeholder="Tìm email, tên, SĐT" value={search} onChange={e=>setSearch(e.target.value)} className="min-w-72 rounded-xl border p-3"/><select value={active} onChange={e=>setActive(e.target.value)} className="rounded-xl border bg-white p-3"><option value="">Mọi trạng thái</option><option value="true">Hoạt động</option><option value="false">Đã khóa</option></select></div>
    <div className="mt-4 overflow-auto rounded-2xl bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">Người dùng</th><th>Vai trò</th><th>Chi nhánh</th><th>Trạng thái</th><th></th></tr></thead><tbody>{items.map(u=><tr key={u.id} className="border-t"><td className="p-4"><strong>{u.displayName}</strong><div className="text-slate-500">{u.email} · {u.phone||'Chưa có SĐT'}</div></td><td>{u.roles.join(', ')||'Chưa gán'}</td><td>{u.branches.map(b=>b.name).join(', ')||'Toàn hệ thống/chưa gán'}</td><td><span className={u.isActive?'text-emerald-700':'text-red-600'}>{u.isActive?'Hoạt động':'Đã khóa'}</span></td><td className="space-x-2 whitespace-nowrap"><button onClick={()=>setSelected(u)} className="rounded-lg border px-3 py-2">Phân quyền</button><button onClick={()=>toggle(u)} className="rounded-lg border px-3 py-2">{u.isActive?'Khóa':'Mở'}</button></td></tr>)}</tbody></table></div>
    {selected&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><div className="max-h-[85vh] w-full max-w-2xl overflow-auto rounded-2xl bg-white p-6"><div className="flex justify-between"><h2 className="text-xl font-bold">Phân quyền: {selected.displayName}</h2><button onClick={()=>setSelected(null)}>✕</button></div><h3 className="mt-5 font-semibold">Vai trò</h3><div className="mt-2 grid gap-2 sm:grid-cols-2">{roles.map(r=><label key={r.id} className="rounded-xl border p-3"><input type="checkbox" checked={selected.roles.includes(r.name)} onChange={e=>role(selected,r,e.target.checked)}/> <strong>{r.name}</strong><div className="ml-5 text-xs text-slate-500">{r.description}</div></label>)}</div><h3 className="mt-5 font-semibold">Chi nhánh được phép truy cập</h3><div className="mt-2 grid gap-2 sm:grid-cols-2">{branches.map(b=><label key={b.id} className="rounded-xl border p-3"><input type="checkbox" checked={selected.branches.some(x=>x.id===b.id)} onChange={e=>branch(selected,b,e.target.checked)}/> {b.code} · {b.name}</label>)}</div></div></div>}
  </section>
}
