import { useEffect, useState } from 'react'
import client from '@/api/client'
import type { ApiError, PermissionResponse, RoleResponse } from '@/types/api'

export default function AdminRoles(){const [roles,setRoles]=useState<RoleResponse[]>([]),[permissions,setPermissions]=useState<PermissionResponse[]>([]),[selected,setSelected]=useState<RoleResponse|null>(null),[open,setOpen]=useState(false),[name,setName]=useState(''),[description,setDescription]=useState(''),[ids,setIds]=useState<string[]>([]),[error,setError]=useState('')
 const load=()=>Promise.all([client.get<RoleResponse[]>('/roles'),client.get<PermissionResponse[]>('/permissions')]).then(([r,p])=>{setRoles(r.data);setPermissions(p.data)})
 useEffect(()=>{load().catch(e=>setError(e.message))},[])
 function edit(r?:RoleResponse){setOpen(true);setSelected(r??null);setName(r?.name??'');setDescription(r?.description??'');setIds(permissions.filter(p=>r?.permissions.includes(p.code)).map(p=>p.id))}
 async function save(){try{const body={name,description:description||null,permissionIds:ids};if(selected)await client.put(`/roles/${selected.id}`,body);else await client.post('/roles',body);setOpen(false);await load()}catch(e){setError((e as ApiError).message)}}
 return <section><div className="flex justify-between"><div><p className="text-sm text-slate-500">RBAC</p><h1 className="text-3xl font-bold">Vai trò & ma trận quyền</h1></div><button onClick={()=>edit()} className="rounded-xl bg-primary-600 px-5 font-semibold text-white">+ Vai trò</button></div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}<div className="mt-6 grid gap-4 lg:grid-cols-2">{roles.map(r=><button key={r.id} onClick={()=>edit(r)} className="rounded-2xl bg-white p-5 text-left shadow-sm"><div className="flex justify-between"><strong className="text-lg">{r.name}</strong><span className="text-sm text-primary-700">Chỉnh sửa</span></div><p className="mt-1 text-sm text-slate-500">{r.description||'Không có mô tả'}</p><div className="mt-3 flex flex-wrap gap-1">{r.permissions.map(p=><span key={p} className="rounded bg-blue-50 px-2 py-1 text-xs text-blue-700">{p}</span>)}</div></button>)}</div>{open&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><div className="max-h-[90vh] w-full max-w-3xl overflow-auto rounded-2xl bg-white p-6"><div className="flex justify-between"><h2 className="text-xl font-bold">{selected?'Sửa vai trò':'Tạo vai trò'}</h2><button onClick={()=>setOpen(false)}>✕</button></div><input value={name} disabled={selected?.name==='Admin'} onChange={e=>setName(e.target.value)} placeholder="Tên vai trò" className="mt-5 w-full rounded-xl border p-3"/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Mô tả" className="mt-3 w-full rounded-xl border p-3"/><div className="mt-4 grid gap-2 sm:grid-cols-2">{permissions.map(p=><label key={p.id} className="rounded-xl border p-3"><input type="checkbox" disabled={selected?.name==='Admin'} checked={ids.includes(p.id)} onChange={e=>setIds(e.target.checked?[...ids,p.id]:ids.filter(x=>x!==p.id))}/> <strong>{p.code}</strong><div className="ml-5 text-xs text-slate-500">{p.description}</div></label>)}</div><button disabled={!name||selected?.name==='Admin'} onClick={save} className="mt-5 w-full rounded-xl bg-primary-600 py-3 font-semibold text-white disabled:opacity-40">Lưu ma trận quyền</button></div></div>}</section>}
