import { useCallback, useEffect, useState } from 'react'
import client from '@/api/client'
import type { ApiError, BranchResponse, PagedResponse } from '@/types/api'
const blank={code:'',name:'',address:'',phone:'',province:'',district:'',ward:''}
export default function AdminBranches(){const [items,setItems]=useState<BranchResponse[]>([]),[form,setForm]=useState(blank),[editing,setEditing]=useState<BranchResponse|null>(null),[error,setError]=useState('')
 const load=useCallback(()=>client.get<PagedResponse<BranchResponse>>('/branches',{params:{pageSize:100,includeInactive:true}}).then(r=>setItems(r.data.items)),[]);useEffect(()=>{load().catch(e=>setError(e.message))},[load])
 function start(b?:BranchResponse){setEditing(b??null);setForm(b?{code:b.code,name:b.name,address:b.address,phone:b.phone??'',province:b.province??'',district:b.district??'',ward:b.ward??''}:blank)}
 async function save(e:React.FormEvent){e.preventDefault();try{if(editing)await client.put(`/branches/${editing.id}`,form);else await client.post('/branches',form);start();await load()}catch(e){setError((e as ApiError).message)}}
 async function toggle(b:BranchResponse){try{await client.patch(`/branches/${b.id}/status`,{isActive:!b.isActive});await load()}catch(e){setError((e as ApiError).message)}}
 return <section><p className="text-sm text-slate-500">Cấu hình toàn hệ thống</p><h1 className="text-3xl font-bold">Quản lý chi nhánh</h1>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}<form onSubmit={save} className="mt-6 grid gap-3 rounded-2xl bg-white p-5 shadow-sm lg:grid-cols-4">{(['code','name','address','phone','province','district','ward'] as const).map(k=><input key={k} required={['code','name','address'].includes(k)} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} placeholder={{code:'Mã chi nhánh',name:'Tên chi nhánh',address:'Địa chỉ',phone:'Điện thoại',province:'Tỉnh/Thành',district:'Quận/Huyện',ward:'Phường/Xã'}[k]} className="rounded-xl border p-3"/>)}<div className="flex gap-2"><button className="flex-1 rounded-xl bg-primary-600 font-semibold text-white">{editing?'Lưu':'Thêm'}</button>{editing&&<button type="button" onClick={()=>start()} className="rounded-xl border px-4">Hủy</button>}</div></form><div className="mt-6 grid gap-4 lg:grid-cols-2">{items.map(b=><article key={b.id} className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex justify-between"><div><span className="text-sm font-semibold text-primary-700">{b.code}</span><h2 className="text-lg font-bold">{b.name}</h2></div><span className={b.isActive?'text-emerald-700':'text-red-600'}>{b.isActive?'Hoạt động':'Tạm dừng'}</span></div><p className="mt-3 text-sm">{b.address}</p><p className="text-sm text-slate-500">{[b.ward,b.district,b.province].filter(Boolean).join(', ')} · {b.phone||'Chưa có SĐT'}</p><div className="mt-4 flex gap-2"><button onClick={()=>start(b)} className="rounded-lg border px-4 py-2">Sửa</button><button onClick={()=>toggle(b)} className="rounded-lg border px-4 py-2">{b.isActive?'Ngừng':'Kích hoạt'}</button></div></article>)}</div></section>}
