import { useCallback, useEffect, useState } from 'react'
import client from '@/api/client'
import type { ApiError, CategoryResponse, PagedResponse } from '@/types/api'
const slugify=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')
export default function Categories(){const [items,setItems]=useState<CategoryResponse[]>([]),[editing,setEditing]=useState<CategoryResponse|null>(null),[name,setName]=useState(''),[slug,setSlug]=useState(''),[parentId,setParentId]=useState(''),[error,setError]=useState('')
 const load=useCallback(()=>client.get<PagedResponse<CategoryResponse>>('/categories',{params:{pageSize:100,includeInactive:true}}).then(r=>setItems(r.data.items)),[]);useEffect(()=>{load().catch(e=>setError(e.message))},[load])
 function start(c?:CategoryResponse){setEditing(c??null);setName(c?.name??'');setSlug(c?.slug??'');setParentId(c?.parentId??'')}
 async function save(e:React.FormEvent){e.preventDefault();try{const body={name,slug:slug||slugify(name),parentId:parentId||null};if(editing)await client.put(`/categories/${editing.id}`,body);else await client.post('/categories',body);start();await load()}catch(e){setError((e as ApiError).message)}}
 async function toggle(c:CategoryResponse){try{await client.patch(`/categories/${c.id}/status`,{isActive:!c.isActive});await load()}catch(e){setError((e as ApiError).message)}}
 return <section><p className="text-sm text-slate-500">Danh mục sản phẩm</p><h1 className="text-3xl font-bold">Cây danh mục thuốc</h1>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}<form onSubmit={save} className="mt-6 grid gap-3 rounded-2xl bg-white p-5 shadow-sm md:grid-cols-4"><input required value={name} onChange={e=>{setName(e.target.value);if(!editing)setSlug(slugify(e.target.value))}} placeholder="Tên danh mục" className="rounded-xl border p-3"/><input required value={slug} onChange={e=>setSlug(e.target.value)} placeholder="slug-khong-dau" className="rounded-xl border p-3"/><select value={parentId} onChange={e=>setParentId(e.target.value)} className="rounded-xl border bg-white p-3"><option value="">Không có danh mục cha</option>{items.filter(x=>x.id!==editing?.id&&x.isActive).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><div className="flex gap-2"><button className="flex-1 rounded-xl bg-primary-600 font-semibold text-white">{editing?'Lưu':'Thêm'}</button>{editing&&<button type="button" onClick={()=>start()} className="rounded-xl border px-3">Hủy</button>}</div></form><div className="mt-6 overflow-auto rounded-2xl bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">Danh mục</th><th>Slug</th><th>Danh mục cha</th><th>Trạng thái</th><th></th></tr></thead><tbody>{items.map(c=><tr key={c.id} className="border-t"><td className="p-4 font-semibold">{c.name}</td><td>{c.slug}</td><td>{c.parentName||'—'}</td><td>{c.isActive?'Hoạt động':'Tạm dừng'}</td><td className="space-x-2"><button onClick={()=>start(c)} className="rounded-lg border px-3 py-2">Sửa</button><button onClick={()=>toggle(c)} className="rounded-lg border px-3 py-2">{c.isActive?'Ngừng':'Bật'}</button></td></tr>)}</tbody></table></div></section>}
