import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import client from '@/api/client'
import { useAuthStore } from '@/auth/store'
import type { OrderResponse, PagedResponse, PrescriptionResponse } from '@/types/api'

export default function Home() {
  const user = useAuthStore((state) => state.user); const canReadOrders = user?.permissions.includes('orders.read') ?? false
  const [counts, setCounts] = useState({ prescriptions: 0, orders: 0 }); const [error, setError] = useState('')
  const load = useCallback(async () => { if (!canReadOrders) return; try { const [p, o] = await Promise.all([client.get<PagedResponse<PrescriptionResponse>>('/prescriptions', { params: { status: 'PENDING', pageSize: 1 } }), client.get<PagedResponse<OrderResponse>>('/orders', { params: { status: 'PENDING', pageSize: 1 } })]); setCounts({ prescriptions: p.data.totalItems, orders: o.data.totalItems }); setError('') } catch (reason) { setError((reason as { message: string }).message) } }, [canReadOrders])
  useEffect(() => { const initial = window.setTimeout(load, 0); const refresh = () => load(); window.addEventListener('focus', refresh); const timer = window.setInterval(load, 15000); return () => { window.clearTimeout(initial); window.removeEventListener('focus', refresh); window.clearInterval(timer) } }, [load])
  if (!canReadOrders) return <section><p className="text-sm text-slate-500">Bàn làm việc kho</p><h1 className="mt-1 text-3xl font-bold">Xin chào, {user?.displayName}</h1><p className="mt-2 text-slate-600">Quản lý tồn kho, lô thuốc và luân chuyển hàng hóa tại các chi nhánh được phân công.</p><Link to="/internal/inventory" className="mt-7 block max-w-xl rounded-2xl bg-primary-700 p-6 text-white shadow-sm"><span className="text-primary-100">Nghiệp vụ kho</span><strong className="mt-3 block text-2xl">Mở quản lý kho thuốc</strong><span className="mt-8 block text-sm font-semibold">Tồn kho · nhập · điều chỉnh · chuyển kho · lịch sử →</span></Link></section>
  return <section><p className="text-sm text-slate-500">Bàn làm việc</p><h1 className="mt-1 text-3xl font-bold">Xin chào, {user?.displayName}</h1><p className="mt-2 text-slate-600">Theo dõi các việc cần xử lý tại chi nhánh được phân công.</p>{error && <p className="mt-5 rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}<div className="mt-7 grid gap-5 md:grid-cols-3"><Link to="/internal/prescriptions" className="rounded-2xl bg-white p-6 shadow-sm"><span className="text-sm text-slate-500">Đơn thuốc chờ duyệt</span><strong className="mt-3 block text-4xl text-amber-600">{counts.prescriptions}</strong><span className="mt-4 block text-sm font-semibold text-primary-700">Mở hàng đợi →</span></Link><Link to="/internal/orders" className="rounded-2xl bg-white p-6 shadow-sm"><span className="text-sm text-slate-500">Đơn hàng chờ xác nhận</span><strong className="mt-3 block text-4xl text-primary-700">{counts.orders}</strong><span className="mt-4 block text-sm font-semibold text-primary-700">Xử lý đơn →</span></Link><Link to="/internal/pos" className="rounded-2xl bg-primary-700 p-6 text-white shadow-sm"><span className="text-sm text-primary-100">Bán hàng tại quầy</span><strong className="mt-3 block text-2xl">Tạo hóa đơn POS</strong><span className="mt-8 block text-sm font-semibold">Bắt đầu bán →</span></Link></div></section>
}
