import { useCallback, useEffect, useState, type FormEvent } from 'react'
import client from '@/api/client'
import { useAuthStore } from '@/auth/store'
import type { ApiError, BatchResponse, InventoryResponse, InventoryTransactionResponse, PagedResponse, ProductResponse } from '@/types/api'
import { dateTime, money } from '@/utils/format'

type Tab = 'stock' | 'receive' | 'adjust' | 'transfer' | 'batches' | 'history'
const today = new Date().toISOString().slice(0, 10)
export default function Inventory() {
  const branches = useAuthStore((state) => state.user?.branches ?? []); const canAdjust = useAuthStore((state) => state.permissions.includes('inventory.adjust'))
  const [tab, setTab] = useState<Tab>('stock'); const [branchId, setBranchId] = useState(branches[0]?.id ?? ''); const [search, setSearch] = useState(''); const [lowStockOnly, setLowStockOnly] = useState(false)
  const [stock, setStock] = useState<InventoryResponse[]>([]); const [batches, setBatches] = useState<BatchResponse[]>([]); const [products, setProducts] = useState<ProductResponse[]>([]); const [history, setHistory] = useState<InventoryTransactionResponse[]>([])
  const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const [receive, setReceive] = useState({ productId: '', batchId: '', quantity: 1, reorderLevel: 10, note: '' })
  const [adjust, setAdjust] = useState({ inventoryKey: '', quantityDelta: 0, reason: '' })
  const [transfer, setTransfer] = useState({ inventoryKey: '', toBranchId: '', quantity: 1, note: '' })
  const [batch, setBatch] = useState({ productId: '', batchNumber: '', mfgDate: today, expiryDate: '', costPrice: 0 })
  const load = useCallback(async () => { const [s, b, p, h] = await Promise.all([
    client.get<PagedResponse<InventoryResponse>>('/inventory', { params: { branchId: branchId || undefined, search: search || undefined, lowStockOnly, pageSize: 100 } }),
    client.get<PagedResponse<BatchResponse>>('/batches', { params: { search: search || undefined, pageSize: 100 } }), client.get<PagedResponse<ProductResponse>>('/products', { params: { pageSize: 100 } }),
    client.get<PagedResponse<InventoryTransactionResponse>>('/inventory/transactions', { params: { branchId: branchId || undefined, pageSize: 100 } }),
  ]); setStock(s.data.items); setBatches(b.data.items); setProducts(p.data.items); setHistory(h.data.items); setError('') }, [branchId, search, lowStockOnly])
  useEffect(() => { const timer = window.setTimeout(() => load().catch((e) => setError(e.message)), 200); return () => window.clearTimeout(timer) }, [load])
  const selectedProductBatches = batches.filter((item) => item.productId === receive.productId && !item.isExpired)
  async function execute(action: () => Promise<unknown>, success: string) { setBusy(true); setError(''); setMessage(''); try { await action(); setMessage(success); await load(); setTab('stock') } catch (e) { setError((e as ApiError).message) } finally { setBusy(false) } }
  function stockFromKey(key: string) { return stock.find((item) => `${item.productId}|${item.batchId}` === key) }
  async function submitReceive(e: FormEvent) { e.preventDefault(); await execute(() => client.post('/inventory/receive', { branchId, ...receive, quantity: Number(receive.quantity), reorderLevel: Number(receive.reorderLevel), note: receive.note || null }), 'Nhập kho thành công.') }
  async function submitAdjust(e: FormEvent) { e.preventDefault(); const item = stockFromKey(adjust.inventoryKey); if (!item) return setError('Hãy chọn dòng tồn kho.'); await execute(() => client.post('/inventory/adjust', { branchId: item.branchId, productId: item.productId, batchId: item.batchId, quantityDelta: Number(adjust.quantityDelta), reason: adjust.reason }), 'Điều chỉnh tồn kho thành công.') }
  async function submitTransfer(e: FormEvent) { e.preventDefault(); const item = stockFromKey(transfer.inventoryKey); if (!item) return setError('Hãy chọn dòng tồn kho.'); await execute(() => client.post('/inventory/transfer', { fromBranchId: item.branchId, toBranchId: transfer.toBranchId, productId: item.productId, batchId: item.batchId, quantity: Number(transfer.quantity), note: transfer.note || null }), 'Chuyển kho thành công.') }
  async function submitBatch(e: FormEvent) { e.preventDefault(); await execute(() => client.post('/batches', { ...batch, costPrice: Number(batch.costPrice) }), 'Tạo lô thuốc thành công.') }
  const input = 'mt-2 w-full rounded-xl border p-3'; const tabs: Array<[Tab, string]> = [['stock','Tồn kho'],['receive','Nhập kho'],['adjust','Điều chỉnh'],['transfer','Chuyển kho'],['batches','Lô thuốc'],['history','Lịch sử']]
  return <section><p className="text-sm text-slate-500">Nhân viên kho</p><h1 className="text-3xl font-bold">Quản lý kho thuốc</h1><div className="mt-5 flex flex-wrap gap-2">{tabs.filter(([key]) => canAdjust || !['receive','adjust','transfer'].includes(key)).map(([key,label]) => <button key={key} onClick={() => { setTab(key); setError(''); setMessage('') }} className={`rounded-xl px-4 py-2 text-sm font-semibold ${tab === key ? 'bg-primary-600 text-white' : 'bg-white text-slate-600'}`}>{label}</button>)}</div>{error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}{message && <p className="mt-4 rounded-xl bg-emerald-50 p-3 text-emerald-700">{message}</p>}
    {(tab === 'stock' || tab === 'history') && <div className="mt-5 grid gap-3 rounded-2xl bg-white p-4 shadow-sm md:grid-cols-[1fr_1fr_auto]"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Tên thuốc, mã thuốc hoặc số lô…" className="rounded-xl border p-3" /><select value={branchId} onChange={(e) => setBranchId(e.target.value)} className="rounded-xl border p-3">{branches.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}</select>{tab === 'stock' && <label className="flex items-center gap-2 px-2"><input type="checkbox" checked={lowStockOnly} onChange={(e) => setLowStockOnly(e.target.checked)} /> Chỉ sắp hết</label>}</div>}
    {tab === 'stock' && <div className="mt-5 overflow-x-auto rounded-2xl bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">Sản phẩm</th><th>Lô/HSD</th><th>Tồn</th><th>Đang giữ</th><th>Khả dụng</th><th>Mức đặt lại</th><th>Cảnh báo</th></tr></thead><tbody>{stock.map((i) => <tr key={`${i.branchId}-${i.productId}-${i.batchId}`} className="border-t"><td className="p-4"><strong>{i.productName}</strong><p className="text-xs text-slate-400">{i.productCode}</p></td><td>{i.batchNumber}<p className="text-xs">{new Date(i.expiryDate).toLocaleDateString('vi-VN')}</p></td><td>{i.quantityOnHand}</td><td>{i.reservedQuantity}</td><td className="font-bold">{i.availableQuantity}</td><td>{i.reorderLevel}</td><td>{i.isExpired ? <span className="text-red-600">Hết hạn</span> : i.isLowStock ? <span className="text-amber-600">Sắp hết</span> : <span className="text-emerald-600">Đủ hàng</span>}</td></tr>)}</tbody></table></div>}
    {tab === 'receive' && <Operation title="Nhập hàng vào kho"><form onSubmit={submitReceive} className="grid gap-4 md:grid-cols-2"><Field label="Chi nhánh"><select required value={branchId} onChange={(e) => setBranchId(e.target.value)} className={input}>{branches.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}</select></Field><Field label="Sản phẩm"><select required value={receive.productId} onChange={(e) => setReceive({ ...receive, productId: e.target.value, batchId: '' })} className={input}><option value="">Chọn sản phẩm</option>{products.map((p) => <option key={p.id} value={p.id}>{p.code} — {p.name}</option>)}</select></Field><Field label="Lô thuốc"><select required value={receive.batchId} onChange={(e) => setReceive({ ...receive, batchId: e.target.value })} className={input}><option value="">Chọn lô còn hạn</option>{selectedProductBatches.map((b) => <option key={b.id} value={b.id}>{b.batchNumber} — HSD {b.expiryDate}</option>)}</select></Field><Field label="Số lượng nhập"><input required min="1" type="number" value={receive.quantity} onChange={(e) => setReceive({ ...receive, quantity: Number(e.target.value) })} className={input} /></Field><Field label="Mức cảnh báo đặt lại"><input min="0" type="number" value={receive.reorderLevel} onChange={(e) => setReceive({ ...receive, reorderLevel: Number(e.target.value) })} className={input} /></Field><Field label="Ghi chú"><input value={receive.note} onChange={(e) => setReceive({ ...receive, note: e.target.value })} className={input} /></Field><Submit busy={busy} text="Xác nhận nhập kho" /></form></Operation>}
    {tab === 'adjust' && <Operation title="Điều chỉnh kiểm kê"><form onSubmit={submitAdjust} className="space-y-4"><StockSelect value={adjust.inventoryKey} setValue={(value) => setAdjust({ ...adjust, inventoryKey: value })} stock={stock} input={input} /><Field label="Chênh lệch (+ tăng, − giảm)"><input required type="number" value={adjust.quantityDelta} onChange={(e) => setAdjust({ ...adjust, quantityDelta: Number(e.target.value) })} className={input} /></Field><Field label="Lý do kiểm kê"><textarea required minLength={3} value={adjust.reason} onChange={(e) => setAdjust({ ...adjust, reason: e.target.value })} className={input} /></Field><Submit busy={busy} text="Ghi nhận điều chỉnh" /></form></Operation>}
    {tab === 'transfer' && <Operation title="Chuyển kho giữa chi nhánh"><form onSubmit={submitTransfer} className="space-y-4"><StockSelect value={transfer.inventoryKey} setValue={(value) => setTransfer({ ...transfer, inventoryKey: value })} stock={stock} input={input} /><Field label="Chi nhánh nhận"><select required value={transfer.toBranchId} onChange={(e) => setTransfer({ ...transfer, toBranchId: e.target.value })} className={input}><option value="">Chọn chi nhánh khác</option>{branches.filter((b) => b.id !== branchId).map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}</select></Field><Field label="Số lượng chuyển"><input required min="1" type="number" value={transfer.quantity} onChange={(e) => setTransfer({ ...transfer, quantity: Number(e.target.value) })} className={input} /></Field><Field label="Ghi chú"><input value={transfer.note} onChange={(e) => setTransfer({ ...transfer, note: e.target.value })} className={input} /></Field><Submit busy={busy} text="Xác nhận chuyển kho" /></form></Operation>}
    {tab === 'batches' && <div className="mt-5 grid gap-5 xl:grid-cols-[380px_1fr]"><Operation title="Tạo lô thuốc"><form onSubmit={submitBatch} className="space-y-3"><Field label="Sản phẩm"><select required value={batch.productId} onChange={(e) => setBatch({ ...batch, productId: e.target.value })} className={input}><option value="">Chọn sản phẩm</option>{products.map((p) => <option key={p.id} value={p.id}>{p.code} — {p.name}</option>)}</select></Field><Field label="Số lô"><input required value={batch.batchNumber} onChange={(e) => setBatch({ ...batch, batchNumber: e.target.value.toUpperCase() })} className={input} /></Field><Field label="Ngày sản xuất"><input required type="date" value={batch.mfgDate} onChange={(e) => setBatch({ ...batch, mfgDate: e.target.value })} className={input} /></Field><Field label="Hạn sử dụng"><input required type="date" min={batch.mfgDate} value={batch.expiryDate} onChange={(e) => setBatch({ ...batch, expiryDate: e.target.value })} className={input} /></Field><Field label="Giá vốn"><input required min="0" type="number" value={batch.costPrice} onChange={(e) => setBatch({ ...batch, costPrice: Number(e.target.value) })} className={input} /></Field><Submit busy={busy} text="Tạo lô" /></form></Operation><div className="overflow-x-auto rounded-2xl bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">Sản phẩm</th><th>Số lô</th><th>NSX</th><th>HSD</th><th>Giá vốn</th></tr></thead><tbody>{batches.map((b) => <tr key={b.id} className="border-t"><td className="p-4">{b.productName}</td><td>{b.batchNumber}</td><td>{b.mfgDate}</td><td className={b.isExpired ? 'text-red-600' : ''}>{b.expiryDate}</td><td>{money(b.costPrice)}</td></tr>)}</tbody></table></div></div>}
    {tab === 'history' && <div className="mt-5 overflow-x-auto rounded-2xl bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">Thời gian</th><th>Thuốc/lô</th><th>Loại</th><th>Số lượng</th><th>Sau giao dịch</th><th>Người thực hiện</th><th>Ghi chú</th></tr></thead><tbody>{history.map((h) => <tr key={h.id} className="border-t"><td className="p-4">{dateTime(h.createdAt)}</td><td>{h.productCode}<p className="text-xs">{h.batchNumber}</p></td><td>{h.transactionType}</td><td className={h.quantity < 0 ? 'text-red-600' : 'text-emerald-600'}>{h.quantity}</td><td>{h.balanceAfter}</td><td>{h.createdByName}</td><td>{h.note}</td></tr>)}</tbody></table></div>}
  </section>
}
function Operation({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mt-5 rounded-2xl bg-white p-6 shadow-sm"><h2 className="mb-4 text-xl font-bold">{title}</h2>{children}</section> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-semibold">{label}{children}</label> }
function Submit({ busy, text }: { busy: boolean; text: string }) { return <button disabled={busy} className="w-full rounded-xl bg-primary-600 py-3 font-semibold text-white disabled:opacity-50">{busy ? 'Đang xử lý…' : text}</button> }
function StockSelect({ value, setValue, stock, input }: { value: string; setValue: (value: string) => void; stock: InventoryResponse[]; input: string }) { return <Field label="Dòng tồn kho"><select required value={value} onChange={(e) => setValue(e.target.value)} className={input}><option value="">Chọn thuốc và lô</option>{stock.filter((i) => !i.isExpired).map((i) => <option key={`${i.productId}-${i.batchId}`} value={`${i.productId}|${i.batchId}`}>{i.productName} · Lô {i.batchNumber} · khả dụng {i.availableQuantity}</option>)}</select></Field> }
