import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import client from '@/api/client'
import { useAuthStore } from '@/auth/store'
import type { PagedResponse, OrderResponse } from '@/types/api'
import { dateTime, money, statusClass, statusLabel } from '@/utils/format'

export default function InternalOrders() {
  const branches = useAuthStore((state) => state.user?.branches ?? []); const [branchId, setBranchId] = useState(''); const [status, setStatus] = useState(''); const [search, setSearch] = useState(''); const [orders, setOrders] = useState<OrderResponse[]>([]); const [error, setError] = useState('')
  const load = useCallback(() => client.get<PagedResponse<OrderResponse>>('/orders', { params: { branchId: branchId || undefined, status: status || undefined, search: search || undefined, pageSize: 100 } }).then((r) => setOrders(r.data.items)), [branchId, status, search])
  useEffect(() => { const timer = window.setTimeout(() => load().then(() => setError('')).catch((e) => setError(e.message)), 200); const refresh = () => load(); window.addEventListener('focus', refresh); return () => { window.clearTimeout(timer); window.removeEventListener('focus', refresh) } }, [load])
  return <section><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-slate-500">Bán hàng</p><h1 className="text-3xl font-bold">Quản lý đơn hàng</h1></div><Link to="/internal/pos" className="rounded-xl bg-primary-600 px-5 py-3 font-semibold text-white">+ Tạo đơn tại quầy</Link></div><div className="mt-6 grid gap-3 rounded-2xl bg-white p-4 shadow-sm md:grid-cols-3"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Mã đơn hoặc tên khách…" className="rounded-xl border p-3" /><select value={branchId} onChange={(e) => setBranchId(e.target.value)} className="rounded-xl border p-3">{branches.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}</select><select value={status} onChange={(e) => setStatus(e.target.value)} className="rounded-xl border p-3"><option value="">Tất cả trạng thái</option><option value="PENDING">Chờ xác nhận</option><option value="CONFIRMED">Đã xác nhận</option><option value="COMPLETED">Hoàn tất</option><option value="CANCELLED">Đã hủy</option></select></div>{error && <p className="mt-4 text-red-600">{error}</p>}<div className="mt-5 overflow-hidden rounded-2xl bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-4">Mã đơn</th><th>Khách hàng</th><th>Hình thức</th><th>Thanh toán</th><th>Tổng tiền</th><th>Trạng thái</th><th></th></tr></thead><tbody>{orders.map((o) => <tr key={o.id} className="border-t"><td className="p-4"><strong>{o.code}</strong><p className="text-xs text-slate-400">{dateTime(o.createdAt)}</p></td><td>{o.customerName}<p className="text-xs text-slate-400">{o.recipientPhone}</p></td><td>{o.orderType === 'POS' ? 'Tại quầy' : o.pickupType === 'SHIPPING' ? 'Giao hàng' : 'Nhận tại quầy'}</td><td>{o.paymentMethod}<p className="text-xs">{statusLabel[o.paymentStatus]}</p></td><td className="font-semibold">{money(o.totalAmount)}</td><td><span className={`rounded-full px-2 py-1 text-xs ${statusClass(o.status)}`}>{statusLabel[o.status]}</span></td><td><Link to={`/internal/orders/${o.id}`} className="font-semibold text-primary-700">Xử lý →</Link></td></tr>)}</tbody></table></div>{!orders.length && <p className="p-10 text-center text-slate-500">Không có đơn hàng.</p>}</div></section>
}
