import { Link } from 'react-router-dom'
import { useCartStore } from '@/cart/store'
import { money } from '@/utils/format'

export default function Cart() {
  const items = useCartStore((state) => state.items); const setQuantity = useCartStore((state) => state.setQuantity); const remove = useCartStore((state) => state.remove)
  const subtotal = items.reduce((sum, item) => sum + item.saleUnit.salePrice * item.quantity, 0)
  if (!items.length) return <div className="rounded-3xl bg-white p-12 text-center"><h1 className="text-2xl font-bold">Giỏ hàng đang trống</h1><Link to="/" className="mt-5 inline-block rounded-xl bg-primary-600 px-5 py-3 text-white">Tiếp tục mua sắm</Link></div>
  return <section><h1 className="mb-6 text-2xl font-bold">Giỏ hàng của bạn</h1><div className="grid gap-6 lg:grid-cols-[1fr_340px]"><div className="space-y-3">{items.map(({ product, saleUnit, quantity }) => <article key={`${product.id}-${saleUnit.id}`} className="flex gap-4 rounded-2xl bg-white p-4 shadow-sm"><div className="grid h-24 w-24 shrink-0 place-items-center rounded-xl bg-primary-50 text-primary-400">{product.imageUrl ? <img src={product.imageUrl} alt={product.name} className="h-full w-full object-contain" /> : product.code}</div><div className="min-w-0 flex-1"><Link to={`/products/${product.id}`} className="font-semibold">{product.name}</Link>{product.rxFlag && <p className="text-xs text-red-600">Yêu cầu đơn thuốc đã duyệt</p>}<p className="mt-1 text-xs text-slate-500">Đơn vị: {saleUnit.unitName}</p><p className="mt-2 font-bold text-primary-700">{money(saleUnit.salePrice)} / {saleUnit.unitName}</p></div><div className="text-right"><input aria-label="Số lượng" min="1" max="999" type="number" value={quantity} onChange={(event) => setQuantity(product.id, saleUnit.id, Number(event.target.value))} className="w-20 rounded-lg border p-2" /><button onClick={() => remove(product.id, saleUnit.id)} className="mt-3 block text-sm text-red-600">Xóa</button></div></article>)}</div>
    <aside className="h-fit rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-bold">Tóm tắt</h2><div className="my-5 flex justify-between"><span>Tạm tính</span><strong>{money(subtotal)}</strong></div><p className="text-xs text-slate-500">Phí vận chuyển, VAT và voucher được backend tính chính xác khi tạo đơn.</p><Link to="/checkout" className="mt-5 block rounded-xl bg-primary-600 py-3 text-center font-semibold text-white">Tiến hành đặt hàng</Link></aside></div></section>
}
