import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Navigate, useNavigate } from 'react-router-dom'
import client from '@/api/client'
import { useAuthStore } from '@/auth/store'
import { useCartStore } from '@/cart/store'
import type { ApiError, BranchResponse, OrderResponse, PagedResponse, PrescriptionResponse, ProductAvailability, VoucherValidation } from '@/types/api'
import { money } from '@/utils/format'

export default function Checkout() {
  const items = useCartStore((state) => state.items); const clear = useCartStore((state) => state.clear); const storedBranch = useCartStore((state) => state.branchId); const storedPrescription = useCartStore((state) => state.prescriptionId); const setStoredBranch = useCartStore((state) => state.setBranch)
  const user = useAuthStore((state) => state.user); const navigate = useNavigate()
  const [branches, setBranches] = useState<BranchResponse[]>([]); const [prescriptions, setPrescriptions] = useState<PrescriptionResponse[]>([]); const [availability, setAvailability] = useState<Record<string, ProductAvailability>>({})
  const [form, setForm] = useState({ branchId: storedBranch ?? '', pickupType: 'SHIPPING', paymentMethod: 'COD', voucherCode: '', prescriptionId: storedPrescription ?? '', customerName: user?.displayName ?? '', email: user?.email ?? '', recipientName: user?.displayName ?? '', recipientPhone: user?.phone ?? '', shippingAddress: '' })
  const [voucher, setVoucher] = useState<VoucherValidation | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const subtotal = useMemo(() => items.reduce((sum, item) => sum + item.saleUnit.salePrice * item.quantity, 0), [items]); const hasRx = items.some((item) => item.product.rxFlag)
  useEffect(() => { Promise.all([client.get<PagedResponse<BranchResponse>>('/branches', { params: { pageSize: 100 } }), user ? client.get<PagedResponse<PrescriptionResponse>>('/prescriptions', { params: { status: 'APPROVED', pageSize: 100 } }) : Promise.resolve({ data: { items: [] } })]).then(([branchResult, prescriptionResult]) => { setBranches(branchResult.data.items); setPrescriptions(prescriptionResult.data.items); const branchId = storedBranch || branchResult.data.items[0]?.id || ''; setForm((current) => ({ ...current, branchId })); setStoredBranch(branchId) }).catch((reason) => setError(reason.message)) }, [setStoredBranch, storedBranch, user])
  useEffect(() => { if (!form.branchId) return; Promise.all(items.map((item) => client.get<ProductAvailability>(`/products/${item.product.id}/availability`, { params: { branchId: form.branchId, saleUnitId: item.saleUnit.id } }))).then((results) => setAvailability(Object.fromEntries(results.map((result, index) => [`${result.data.productId}-${items[index].saleUnit.id}`, result.data])))).catch(() => setAvailability({})) }, [form.branchId, items])
  const validPrescriptions = prescriptions.filter((p) => p.branchId === form.branchId && items.filter((item) => item.product.rxFlag).every((cart) => p.items.some((approved) => approved.productId === cart.product.id && approved.approvedQuantity >= cart.quantity * cart.saleUnit.conversionFactor)))
  async function validateVoucher() { if (!form.voucherCode.trim()) return setVoucher(null); if (!user && !form.recipientPhone.trim()) return setError('Khách vãng lai cần nhập số điện thoại trước khi áp dụng voucher.'); setError(''); try { const response = await client.get<VoucherValidation>(`/vouchers/validate/${encodeURIComponent(form.voucherCode.trim())}`, { params: { orderAmount: subtotal, customerPhone: user ? undefined : form.recipientPhone.trim() } }); setVoucher(response.data) } catch (reason) { setError((reason as ApiError).message) } }
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); if (hasRx && !user) return navigate('/login', { state: { from: { pathname: '/checkout' } } }); if (hasRx && !form.prescriptionId) return setError('Giỏ hàng có thuốc kê đơn; hãy chọn đơn thuốc đã duyệt phù hợp.'); const shortage = items.find((item) => (availability[`${item.product.id}-${item.saleUnit.id}`]?.availableQuantity ?? 0) < item.quantity); if (shortage) return setError(`${shortage.product.name} không đủ tồn tại chi nhánh này.`); setBusy(true)
    const order = { branchId: form.branchId, prescriptionId: form.prescriptionId || null, orderType: 'ONLINE', pickupType: form.pickupType, paymentMethod: form.paymentMethod, voucherCode: form.voucherCode.trim() || null, recipientName: form.recipientName, recipientPhone: form.recipientPhone, shippingAddress: form.pickupType === 'SHIPPING' ? form.shippingAddress : null, items: items.map((item) => ({ productId: item.product.id, saleUnitId: item.saleUnit.id, quantity: item.quantity })) }
    try { const response = user ? await client.post<OrderResponse>('/orders', order) : await client.post<OrderResponse>('/orders/guest', { customerName: form.customerName, phone: form.recipientPhone, email: form.email || null, order }); clear(); navigate('/order-success', { state: { order: response.data, authenticated: Boolean(user) } }) }
    catch (reason) { setError((reason as ApiError).message) } finally { setBusy(false) }
  }
  if (!items.length) return <Navigate to="/cart" replace />
  const input = 'mt-2 w-full rounded-xl border border-slate-200 p-3'
  const estimatedDiscount = voucher?.isValid ? voucher.discountAmount : 0
  return <form onSubmit={submit}><h1 className="mb-6 text-2xl font-bold">Thanh toán</h1>{error && <p className="mb-4 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}<div className="grid gap-6 lg:grid-cols-[1fr_360px]"><div className="space-y-5">
    <section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-bold">1. Chi nhánh và tồn kho</h2><select required value={form.branchId} onChange={(e) => { setForm({ ...form, branchId: e.target.value, prescriptionId: '' }); setStoredBranch(e.target.value) }} className={input}><option value="">Chọn chi nhánh</option>{branches.map((b) => <option key={b.id} value={b.id}>{b.name} — {b.address}</option>)}</select><div className="mt-3 space-y-1 text-sm">{items.map((item) => <p key={`${item.product.id}-${item.saleUnit.id}`}>{item.product.name} ({item.saleUnit.unitName}): <strong>{availability[`${item.product.id}-${item.saleUnit.id}`]?.availableQuantity ?? '…'} khả dụng</strong></p>)}</div></section>
    {hasRx && <section className="rounded-2xl border border-red-100 bg-white p-6 shadow-sm"><h2 className="font-bold text-red-700">2. Đơn thuốc</h2><p className="mt-1 text-sm text-slate-500">Chỉ hiển thị đơn đã duyệt, đúng chi nhánh, sản phẩm và số lượng.</p><select required value={form.prescriptionId} onChange={(e) => setForm({ ...form, prescriptionId: e.target.value })} className={input}><option value="">Chọn đơn thuốc</option>{validPrescriptions.map((p) => <option key={p.id} value={p.id}>{p.patientName} — {new Date(p.createdAt).toLocaleDateString('vi-VN')}</option>)}</select>{!validPrescriptions.length && <p className="mt-3 text-sm text-red-600">Chưa có đơn phù hợp. Hãy upload và chờ dược sĩ duyệt.</p>}</section>}
    <section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-bold">{hasRx ? '3' : '2'}. Thông tin người đặt</h2>{!user && <div className="mt-4 grid gap-3 sm:grid-cols-2"><input required placeholder="Họ và tên người đặt" value={form.customerName} onChange={(e) => setForm({ ...form, customerName: e.target.value, recipientName: e.target.value })} className={input} /><input type="email" placeholder="Email (không bắt buộc)" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className={input} /></div>}<div className="mt-4 flex gap-5"><label><input type="radio" checked={form.pickupType === 'SHIPPING'} onChange={() => setForm({ ...form, pickupType: 'SHIPPING' })} /> Giao hàng tận nơi</label><label><input type="radio" checked={form.pickupType === 'STORE_PICKUP'} onChange={() => setForm({ ...form, pickupType: 'STORE_PICKUP' })} /> Nhận tại nhà thuốc</label></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><input required placeholder="Người nhận" value={form.recipientName} onChange={(e) => setForm({ ...form, recipientName: e.target.value })} className={input} /><input required placeholder="Số điện thoại" value={form.recipientPhone} onChange={(e) => { setForm({ ...form, recipientPhone: e.target.value }); if (!user) setVoucher(null) }} className={input} />{form.pickupType === 'SHIPPING' && <textarea required placeholder="Địa chỉ giao hàng" value={form.shippingAddress} onChange={(e) => setForm({ ...form, shippingAddress: e.target.value })} className={`${input} sm:col-span-2`} />}</div></section>
    <section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-bold">Thanh toán</h2><select value={form.paymentMethod} onChange={(e) => setForm({ ...form, paymentMethod: e.target.value })} className={input}><option value="COD">Thanh toán khi nhận hàng (COD)</option><option value="VIETQR">Chuyển khoản VIETQR</option></select>{form.paymentMethod === 'VIETQR' && <p className="mt-2 text-sm text-amber-700">Mã QR đúng số tiền và nội dung chuyển khoản sẽ hiện ngay sau khi tạo đơn.</p>}</section>
  </div><aside className="h-fit rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-bold">Đơn hàng</h2>{items.map((item) => <div key={`${item.product.id}-${item.saleUnit.id}`} className="mt-3 flex justify-between text-sm"><span>{item.product.name} × {item.quantity} {item.saleUnit.unitName}</span><span>{money(item.saleUnit.salePrice * item.quantity)}</span></div>)}<div className="mt-5"><label className="text-sm font-semibold">Voucher</label><div className="mt-2 flex gap-2"><input placeholder="Nhập mã giảm giá" value={form.voucherCode} onChange={(e) => { setForm({ ...form, voucherCode: e.target.value.toUpperCase() }); setVoucher(null) }} className="min-w-0 flex-1 rounded-lg border p-2" /><button type="button" disabled={!form.voucherCode.trim()} onClick={validateVoucher} className="rounded-lg bg-slate-100 px-3 disabled:opacity-50">Áp dụng</button></div><p className="mt-1 text-xs text-slate-500">Khách vãng lai dùng số điện thoại để giới hạn lượt sử dụng.</p></div>{voucher && <p className={`mt-2 text-sm ${voucher.isValid ? 'text-emerald-700' : 'text-red-600'}`}>{voucher.isValid ? `Áp dụng ${voucher.code}: giảm ${money(voucher.discountAmount)}` : voucher.message}</p>}<div className="mt-6 space-y-2 border-t pt-4"><div className="flex justify-between"><span>Tạm tính</span><strong>{money(subtotal)}</strong></div>{estimatedDiscount > 0 && <><div className="flex justify-between text-emerald-700"><span>Giảm giá</span><strong>-{money(estimatedDiscount)}</strong></div><div className="flex justify-between text-lg"><span>Dự kiến sau giảm</span><strong>{money(Math.max(0, subtotal - estimatedDiscount))}</strong></div></>}<p className="mt-2 text-xs text-slate-500">Phí giao hàng và tổng chính xác do backend tính khi tạo đơn.</p></div>{!user && !hasRx && <p className="mt-4 rounded-lg bg-blue-50 p-3 text-xs text-blue-700">Thuốc không kê đơn có thể đặt ngay mà không cần tài khoản.</p>}<button disabled={busy} className="mt-5 w-full rounded-xl bg-primary-600 py-3 font-semibold text-white disabled:opacity-60">{busy ? 'Đang đặt…' : hasRx && !user ? 'Đăng nhập để mua thuốc kê đơn' : 'Hoàn tất đặt hàng'}</button></aside></div></form>
}
