import { useCallback, useEffect, useState } from 'react'
import { Link, useLocation, useParams } from 'react-router-dom'
import client from '@/api/client'
import type { ApiError, OrderResponse } from '@/types/api'
import { dateTime, money, statusClass, statusLabel } from '@/utils/format'
import VietQrPayment from '@/components/VietQrPayment'

export default function OrderDetail() {
  const { id } = useParams(); const location = useLocation(); const [order, setOrder] = useState<OrderResponse | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const load = useCallback(() => client.get<OrderResponse>(`/orders/${id}`).then((response) => setOrder(response.data)).catch((reason) => setError(reason.message)), [id])
  useEffect(() => { load() }, [load])
  async function cancel() { if (!window.confirm('Bạn chắc chắn muốn hủy đơn hàng này?')) return; setBusy(true); try { await client.post(`/orders/${id}/cancel`, { note: 'Khách hàng hủy đơn trên website' }); await load() } catch (reason) { setError((reason as ApiError).message) } finally { setBusy(false) } }
  if (!order) return <p>{error || 'Đang tải đơn hàng…'}</p>
  return <section><Link to="/orders" className="text-sm text-primary-700">← Danh sách đơn hàng</Link>{(location.state as { created?: boolean } | null)?.created && <p className="mt-4 rounded-xl bg-emerald-50 p-4 text-emerald-700">Đặt hàng thành công. Mã đơn: <strong>{order.code}</strong></p>}{error && <p className="mt-4 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}<div className="mt-5 grid gap-6 lg:grid-cols-[1fr_350px]"><div className="space-y-5"><article className="rounded-2xl bg-white p-6 shadow-sm"><div className="flex justify-between"><div><h1 className="text-2xl font-bold">{order.code}</h1><p className="text-sm text-slate-500">{dateTime(order.createdAt)}</p></div><span className={`h-fit rounded-full px-3 py-1 text-sm font-semibold ${statusClass(order.status)}`}>{statusLabel[order.status]}</span></div><div className="mt-5 space-y-4">{order.items.map((item) => <div key={item.id} className="flex justify-between border-t pt-4"><div><strong>{item.productName}</strong><p className="text-sm text-slate-500">{item.productCode} · SL {item.quantity}</p></div><strong>{money(item.lineTotal)}</strong></div>)}</div></article><article className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-bold">Lịch sử xử lý</h2>{order.statusHistory.map((item, index) => <div key={`${item.changedAt}-${index}`} className="mt-4 border-l-2 border-primary-200 pl-4"><strong>{statusLabel[item.toStatus] ?? item.toStatus}</strong><p className="text-sm text-slate-500">{dateTime(item.changedAt)} · {item.changedByName}</p>{item.note && <p className="text-sm">{item.note}</p>}</div>)}</article></div>
    <aside className="h-fit rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-bold">Thông tin thanh toán</h2><dl className="mt-4 space-y-2 text-sm"><div className="flex justify-between"><dt>Tiền hàng</dt><dd>{money(order.subtotalBeforeVat + order.totalVatAmount)}</dd></div><div className="flex justify-between"><dt>Phí giao hàng</dt><dd>{money(order.shippingFee)}</dd></div><div className="flex justify-between text-emerald-700"><dt>Giảm giá</dt><dd>-{money(order.discountAmount)}</dd></div><div className="flex justify-between border-t pt-3 text-lg font-bold"><dt>Tổng cộng</dt><dd>{money(order.totalAmount)}</dd></div></dl><p className="mt-4 text-sm">{order.paymentMethod} · <span className={statusClass(order.paymentStatus)}>{statusLabel[order.paymentStatus]}</span></p><VietQrPayment order={order} />{order.pickupType === 'SHIPPING' && <div className="mt-5 border-t pt-4 text-sm"><strong>Giao đến</strong><p>{order.recipientName} · {order.recipientPhone}</p><p className="text-slate-500">{order.shippingAddress}</p></div>}{(order.status === 'PENDING' || order.status === 'CONFIRMED') && <button disabled={busy} onClick={cancel} className="mt-5 w-full rounded-xl border border-red-200 py-3 font-semibold text-red-600">{busy ? 'Đang hủy…' : 'Hủy đơn hàng'}</button>}</aside></div></section>
}
