import { useEffect, useState, type FormEvent } from 'react'
import client from '@/api/client'
import type { ApiError, BranchResponse, PagedResponse, PrescriptionResponse } from '@/types/api'
import { dateTime, statusClass, statusLabel } from '@/utils/format'
import { useNavigate } from 'react-router-dom'
import { useCartStore } from '@/cart/store'
import type { ProductResponse } from '@/types/api'

export default function Prescriptions() {
  const navigate = useNavigate(); const addToCart = useCartStore((state) => state.add); const setBranch = useCartStore((state) => state.setBranch); const setPrescription = useCartStore((state) => state.setPrescription)
  const [items, setItems] = useState<PrescriptionResponse[]>([]); const [branches, setBranches] = useState<BranchResponse[]>([]); const [form, setForm] = useState({ branchId: '', patientName: '' }); const [image, setImage] = useState<File | null>(null); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [busy, setBusy] = useState(false)
  async function load() { const [p, b] = await Promise.all([client.get<PagedResponse<PrescriptionResponse>>('/prescriptions', { params: { pageSize: 100 } }), client.get<PagedResponse<BranchResponse>>('/branches', { params: { pageSize: 100 } })]); setItems(p.data.items); setBranches(b.data.items); setForm((current) => ({ ...current, branchId: current.branchId || b.data.items[0]?.id || '' })) }
  useEffect(() => { const timer = window.setTimeout(() => load().catch((reason) => setError(reason.message)), 0); return () => window.clearTimeout(timer) }, [])
  async function upload(event: FormEvent) { event.preventDefault(); if (!image) return setError('Hãy chọn ảnh đơn thuốc.'); setBusy(true); setError(''); setSuccess(''); const data = new FormData(); data.append('branchId', form.branchId); data.append('patientName', form.patientName); data.append('image', image)
    try { await client.post('/prescriptions', data); setSuccess('Đã gửi đơn thuốc. Dược sĩ sẽ kiểm tra và phản hồi.'); setForm((current) => ({ ...current, patientName: '' })); setImage(null); await load() } catch (reason) { setError((reason as ApiError).message) } finally { setBusy(false) }
  }
  async function viewImage(id: string) { const preview=window.open('about:blank','_blank');if(preview){preview.document.title='Đang tải đơn thuốc...';preview.document.body.innerHTML='<p style="font-family:sans-serif;padding:24px">Đang tải ảnh đơn thuốc...</p>'}try { const response = await client.get(`/prescriptions/${id}/image`, { responseType: 'blob' }); const url = URL.createObjectURL(response.data);if(preview){preview.opener=null;preview.location.href=url}else{window.location.assign(url)}window.setTimeout(() => URL.revokeObjectURL(url), 60_000) } catch (reason) { preview?.close();setError((reason as ApiError).message) } }
  async function buyApproved(prescription: PrescriptionResponse) { setError(''); try { const products = await Promise.all(prescription.items.map((item) => client.get<ProductResponse>(`/products/${item.productId}`))); for (const response of products) { const approved = prescription.items.find((item) => item.productId === response.data.id)!; const unit = [...response.data.saleUnits].filter((item) => item.isActive && item.conversionFactor <= approved.approvedQuantity && approved.approvedQuantity % item.conversionFactor === 0).sort((a, b) => b.conversionFactor - a.conversionFactor)[0]; if (!unit) throw new Error(`Không có đơn vị bán phù hợp cho ${response.data.name}.`); addToCart(response.data, Math.floor(approved.approvedQuantity / unit.conversionFactor), unit) } setBranch(prescription.branchId); setPrescription(prescription.id); navigate('/cart') } catch (reason) { setError((reason as ApiError).message ?? 'Không thể tạo giỏ hàng theo đơn.') } }
  return <section><h1 className="text-2xl font-bold">Đơn thuốc của tôi</h1><div className="mt-6 grid gap-6 lg:grid-cols-[380px_1fr]"><form onSubmit={upload} className="h-fit rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-bold">Gửi đơn thuốc mới</h2>{error && <p className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{success && <p className="mt-3 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{success}</p>}<label className="mt-4 block text-sm">Chi nhánh<select required value={form.branchId} onChange={(e) => setForm({ ...form, branchId: e.target.value })} className="mt-2 w-full rounded-xl border p-3">{branches.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="mt-4 block text-sm">Tên bệnh nhân<input required minLength={2} value={form.patientName} onChange={(e) => setForm({ ...form, patientName: e.target.value })} className="mt-2 w-full rounded-xl border p-3" /></label><label className="mt-4 block text-sm">Ảnh JPEG, PNG hoặc WebP (tối đa 5 MB)<input required accept="image/jpeg,image/png,image/webp" type="file" onChange={(e) => setImage(e.target.files?.[0] ?? null)} className="mt-2 block w-full text-sm" /></label><button disabled={busy} className="mt-5 w-full rounded-xl bg-primary-600 py-3 font-semibold text-white">{busy ? 'Đang gửi…' : 'Gửi dược sĩ duyệt'}</button></form>
    <div className="space-y-4">{items.length === 0 && <div className="rounded-2xl bg-white p-8 text-center text-slate-500">Chưa có đơn thuốc. Hãy gửi ảnh đơn hoặc yêu cầu tư vấn để dược sĩ duyệt thuốc phù hợp.</div>}{items.map((p) => <article key={p.id} className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><h2 className="font-bold">Bệnh nhân: {p.patientName}</h2><p className="mt-1 text-sm text-slate-500">{p.branchName} · {dateTime(p.createdAt)}</p><button onClick={() => viewImage(p.id)} className="mt-2 text-sm font-semibold text-primary-700">Xem ảnh đã gửi</button></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${statusClass(p.status)}`}>{statusLabel[p.status]}</span></div>{p.pharmacistNote && <p className="mt-4 rounded-xl bg-slate-50 p-3 text-sm"><strong>Phản hồi dược sĩ:</strong> {p.pharmacistNote}</p>}{p.items.length > 0 && <div className="mt-4 border-t pt-3 text-sm">{p.items.map((item) => <p key={item.id}><strong>{item.productName}</strong> × {item.approvedQuantity} — {item.dosage}{item.instructions ? ` (${item.instructions})` : ''}</p>)}</div>}{p.status === 'APPROVED' && p.items.length > 0 && <button onClick={() => buyApproved(p)} className="mt-4 w-full rounded-xl bg-primary-600 py-3 font-semibold text-white">Mua thuốc theo đơn đã duyệt</button>}</article>)}</div></div></section>
}
