import { useState, type FormEvent } from 'react'
import client from '@/api/client'
import { useAuthStore } from '@/auth/store'
import type { ApiError, CurrentUser } from '@/types/api'

export default function Profile() {
  const user = useAuthStore((state) => state.user)!; const setUser = useAuthStore((state) => state.setUser); const clearSession = useAuthStore((state) => state.clearSession)
  const [profile, setProfile] = useState({ displayName: user.displayName, phone: user.phone ?? '' }); const [password, setPassword] = useState({ currentPassword: '', newPassword: '', confirm: '' }); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  async function saveProfile(event: FormEvent) { event.preventDefault(); setError(''); setMessage(''); try { await client.put('/auth/me', { displayName: profile.displayName, phone: profile.phone || null }); const response = await client.get<CurrentUser>('/auth/me'); setUser(response.data); setMessage('Đã cập nhật hồ sơ.') } catch (reason) { setError((reason as ApiError).message) } }
  async function changePassword(event: FormEvent) { event.preventDefault(); setError(''); setMessage(''); if (password.newPassword !== password.confirm) return setError('Mật khẩu xác nhận không khớp.'); try { await client.post('/auth/change-password', { currentPassword: password.currentPassword, newPassword: password.newPassword }); clearSession(); window.location.assign('/login') } catch (reason) { setError((reason as ApiError).message) } }
  const input = 'mt-2 w-full rounded-xl border p-3'
  return <section><h1 className="text-2xl font-bold">Hồ sơ cá nhân</h1>{message && <p className="mt-4 rounded-xl bg-emerald-50 p-4 text-emerald-700">{message}</p>}{error && <p className="mt-4 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}<div className="mt-6 grid gap-6 lg:grid-cols-2"><form onSubmit={saveProfile} className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-bold">Thông tin tài khoản</h2><label className="mt-4 block text-sm">Email<input disabled value={user.email} className={`${input} bg-slate-50`} /></label><label className="mt-4 block text-sm">Họ và tên<input required minLength={2} value={profile.displayName} onChange={(e) => setProfile({ ...profile, displayName: e.target.value })} className={input} /></label><label className="mt-4 block text-sm">Số điện thoại<input value={profile.phone} onChange={(e) => setProfile({ ...profile, phone: e.target.value })} className={input} /></label><button className="mt-5 rounded-xl bg-primary-600 px-5 py-3 font-semibold text-white">Lưu thay đổi</button></form>
    <form onSubmit={changePassword} className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-bold">Đổi mật khẩu</h2><label className="mt-4 block text-sm">Mật khẩu hiện tại<input required type="password" value={password.currentPassword} onChange={(e) => setPassword({ ...password, currentPassword: e.target.value })} className={input} /></label><label className="mt-4 block text-sm">Mật khẩu mới<input required minLength={8} type="password" value={password.newPassword} onChange={(e) => setPassword({ ...password, newPassword: e.target.value })} className={input} /></label><label className="mt-4 block text-sm">Xác nhận mật khẩu<input required type="password" value={password.confirm} onChange={(e) => setPassword({ ...password, confirm: e.target.value })} className={input} /></label><button className="mt-5 rounded-xl bg-slate-800 px-5 py-3 font-semibold text-white">Đổi mật khẩu</button><p className="mt-3 text-xs text-slate-500">Bạn sẽ được đăng xuất khỏi tất cả phiên sau khi đổi mật khẩu.</p></form></div></section>
}
